In [8]:
import pandas as pd


df = pd.read_csv(
    "../data/processed/hotel_bookings_categorized.csv",
    dtype=str
)

# Kontingenční tabulka – typ hotelu a zrušení rezervace

In [9]:
hotel_table = pd.crosstab(df["hotel"], df["is_canceled"])

hotel_table = hotel_table.rename(columns={
    "0": "Nezrušeno",
    "1": "Zrušeno"
})

hotel_table["Celkem"] = hotel_table.sum(axis=1)
hotel_table["Podíl zrušení (%)"] = (
    hotel_table["Zrušeno"] / hotel_table["Celkem"] * 100
).round(1)

display(hotel_table)

is_canceled   Nezrušeno  Zrušeno  Celkem  Podíl zrušení (%)
hotel
City Hotel        45833    33061   78894               41.9
Resort Hotel      28554    11110   39664               28.0

# Kontingenční tabulka – tržní segment a zrušení rezervace

In [10]:
segment_table = pd.crosstab(df["market_segment"], df["is_canceled"])

segment_table = segment_table.rename(columns={
    "0": "Nezrušeno",
    "1": "Zrušeno"
})

segment_table["Celkem"] = segment_table.sum(axis=1)
segment_table["Podíl zrušení (%)"] = (
    segment_table["Zrušeno"] / segment_table["Celkem"] * 100
).round(1)

display(segment_table.sort_values("Podíl zrušení (%)", ascending=False))

is_canceled     Nezrušeno  Zrušeno  Celkem  Podíl zrušení (%)
market_segment
Groups               7665    12093   19758               61.2
Online TA           35406    20722   56128               36.9
Offline TA/TO       15748     8300   24048               34.5
Aviation              180       51     231               22.1
Corporate            4242      989    5231               18.9
Direct              10518     1929   12447               15.5
Complementary         628       87     715               12.2